### ISSUE TITLE
Adding GAP syntax highlighting

### ISSUE THREAD

**Issue by olexandr-konovalov** [carpentries-incubator/gap-lesson#2]
Currently the GAP input is labeled using `{.gap}` but this is rather something for the future - at the moment, this is not supported (can't find the link to confirm this, but I think to make this working, one should have GAP syntax support for pandoc).

**Comment by alex-konovalov** [comment]
See now the discussion on this here: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-December/003582.html

**Comment by olexandr-konovalov** [comment]
This issue still makes sense, but first we would have to migrate to the Workbench, and then investigate if something can be done.

**Comment by olexandr-konovalov** [comment]
It will hopefully work now: https://carpentries.github.io/sandpaper-docs/episodes.html#code-blocks-with-syntax-highlighting explains how to use syntax highlighting, referring to https://github.com/jgm/skylighting/tree/master/skylighting-core/xml for the list of supported languages, which, thanks to @ChrisJefferson's suggestion at https://github.com/jgm/skylighting/issues/167, now has GAP

**Comment by olexandr-konovalov** [comment]
It works, although not all the time ideally - I will submit a PR anyway, it's better than without it. Compare
<img width="375" alt="Screenshot 2024-08-28 at 15 00 38" src="https://github.com/user-attachments/assets/2941b195-56c9-4f78-9d50-6db06b3cf4d4">
and
<img width="358" alt="Screenshot 2024-08-28 at 15 00 53" src="https://github.com/user-attachments/assets/27a3bf92-1cac-4685-8fe3-41e4868ba3fc">
